import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import {NextUIProvider} from "@nextui-org/react";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Elsie Hair Salon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  data-theme="light">
      <body className={inter.className}>
        <Navigation />
        <div className='p-2'>
       {children}
       </div>
       <Footer />
      </body>
    </html>
  );
}
