import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
import Footer2 from "@/components/Footer2";
import { NextUIProvider } from "@nextui-org/react";
import { ThemeModeScript, DarkThemeToggle, Flowbite } from "flowbite-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Elsie Hair Salon",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Flowbite>
      <html lang="en">
        <head>
          <ThemeModeScript />
        </head>
        <body className={inter.className}>
          <Navigation />

          {children}

          <Footer />
        </body>
      </html>
    </Flowbite>
  );
}
